name: CI

on:
  push:
  pull_request:

jobs:
  freebsd-build:
    runs-on: ubuntu-latest
    env:
      FREEBSD_VERSION: '15.1'
    steps:
      - name: Repository checkout
        uses: actions/checkout@v6

      - uses: cross-platform-actions/action@v1.4.0
        with:
          operating_system: 'freebsd'
          version: '${{ env.FREEBSD_VERSION }}'
          architecture: 'x86_64'

      - name: Build on FreeBSD
        shell: cpa.sh {0}
        run: |
          # Use latest package set
          sudo mkdir -p /usr/local/etc/pkg/repos/
          sudo cp /etc/pkg/FreeBSD.conf /usr/local/etc/pkg/repos/FreeBSD.conf
          sudo sed -i.bak -e 's|/quarterly|/latest|' /usr/local/etc/pkg/repos/FreeBSD.conf

          # Install deps
          sudo -E pkg install -y evdev-proto meson ninja pkgconf

          # Run the build
          env CPPFLAGS='-isystem /usr/local/include' CFLAGS='-isystem /usr/local/include' meson _build
          ninja -v -C _build

  dragonfly-build:
    runs-on: ubuntu-latest
    env:
      DFLY_VERSION: '6.4.2'
    steps:
      - name: Repository checkout
        uses: actions/checkout@v6

      - uses: cross-platform-actions/action@v1.4.0
        with:
          operating_system: 'dragonflybsd'
          version: '${{ env.DFLY_VERSION }}'
          architecture: 'x86_64'

      - name: Build on DragonFly
        shell: cpa.sh {0}
        run: |
          # Install deps
          sudo -E pkg install -y evdev-proto meson ninja pkgconf

          # Run the build
          env CPPFLAGS='-isystem /usr/local/include' CFLAGS='-isystem /usr/local/include' meson _build
          ninja -v -C _build

  netbsd-build:
    runs-on: ubuntu-latest
    env:
      NETBSD_VERSION: '11.0'
    steps:
      - name: Repository checkout
        uses: actions/checkout@v6

      - uses: cross-platform-actions/action@v1.4.0
        with:
          operating_system: 'netbsd'
          version: '${{ env.NETBSD_VERSION }}'
          architecture: 'x86_64'

      - name: Build on NetBSD
        shell: cpa.sh {0}
        run: |
          # Set PKG_PATH for package repository
          export PKG_PATH="https://cdn.NetBSD.org/pub/pkgsrc/packages/NetBSD/amd64/${{ env.NETBSD_VERSION }}/All"

          # Install deps
          sudo -E pkg_add meson ninja-build pkgconf ndevd

          # Run the build
          env CPPFLAGS='-isystem /usr/pkg/include' CFLAGS='-isystem /usr/pkg/include' meson _build
          ninja -v -C _build

  openbsd-build:
    runs-on: ubuntu-latest
    env:
      OPENBSD_VERSION: '7.9'
    steps:
      - name: Repository checkout
        uses: actions/checkout@v6

      - uses: cross-platform-actions/action@v1.4.0
        with:
          operating_system: 'openbsd'
          version: '${{ env.OPENBSD_VERSION }}'
          architecture: 'x86_64'

      - name: Build on OpenBSD
        shell: cpa.sh {0}
        run: |
          # Install deps
          sudo -E pkg_add meson ninja pkgconf

          # Run the build
          env CPPFLAGS='-isystem /usr/local/include' CFLAGS='-isystem /usr/local/include' meson _build
          ninja -v -C _build
